# Name: Shubham Sharma
## IIT BOMBAY
This file has the codes of how we can find dimension of null space of a matrix and dimension of eigen space 

In [1]:
import numpy as np
np.set_printoptions(precision=16)
import math

In [2]:
#algorithm to find the index of first non-zero element in a column from position start_row 
def find_nonzero_element_index(col, start_row):
    #print(col)
    ret_index = -1
    for k in np.arange(start_row,col.size):
        #print('is close to zero: %s' %(math.isclose(np.abs(col[k]), 0., abs_tol=1e-13)))
        if not math.isclose(np.abs(col[k]), 0., abs_tol=1e-13):
            ret_index = k
            break
    #print ('ret index: %d' %(ret_index))
    return ret_index

In [3]:
#algorithm to convert a matrix A to rref
#algorithm to convert a matrix A to rref
def find_rref(A):
    #print(A.shape)
    m = (A.shape)[0] #num rows
    n = (A.shape)[1] #num cols
    print('num rows: %d' %(m))
    print('num cols: %d' %(n))

    j = 0
    r = 0
    
    B=A.copy()
    
    for j in np.arange(0,n):
        non_zero_row_index = find_nonzero_element_index(B[:,j],r)
        #print('r: %d' %(r))
        if non_zero_row_index != -1: 
            #write the code to make the pivot element in the non-zero row as 1 
            #and to make all other elements in the pivot column as zero  
            
            #If non_zero index is greater than the r then we will interschange the two rows
            if non_zero_row_index>r:
                c=r
                B[[non_zero_row_index,r]]=B[[r,non_zero_row_index]]
            else:
                c=non_zero_row_index
            B[c,:]=B[c,:]/B[c,j]
            
            
            #performimg the row operations
            for i in range(m):
                if i!=c:
                    B[i,:]=B[i,:]-B[i,j]*B[c,:]
            
            #you can check your code by printing the intermediate matrix using the following statement
            #print('rref process in col: %d ' %(j))
            #print(A)
            r = r+1
    return (B)



## The Above codes are basically the function to find RREF of a matrix  from the very last assignment


## The function extract_pivot_column is a function that is made by making some changes in the function to find the column space from the last assignment

In [4]:
#Defining a function to find the pivot columns in the matrices , so we know that only those columns are the one which are pivot columns
def extract_pivot_column(A):
    #B=find_rref(A)
    #Finding the pivot columns index
    B=find_rref(A)
    #print('The rref of the given matrix is : ',)
    x=[]
    (m,n)=B.shape
    for i in range(m):
        for j in range(n):
            if B[i,j]==1:
                x.append(j)
                break    
    
    #column_basis=[]
    #for k in x:
    #    column_basis.append(A[:,k])
    
    return x

## Now Let us define the function to find the null space of a matrix , it is using the above functions to find the pivot columns and the rref of the matrix. 

In [5]:
# Now lets find the Null space of this matrix

def null_space(B):
    #Finding the rref of the matrix B
    A=find_rref(B)
    #b is an array that will give us the index of the pivot columns
    b=extract_pivot_column(A)
    #counter=0
    null_space=[]
    m,n=A.shape
    #We know that the dim of the null space is n-dim of the column space or n- (no of pivot columns) ,  so we are running loop for n-len(b) times basically , so that every time it gives a vector in the null space
    for i in range(n):
        if i not in b:
            #Firsty initializing a matrix [0] of n*1
            dummy=np.zeros([n,1])
            #we can take any non-zero value to dummy[i]
            #For the sake of convinience, giving it a value of 1
            #Basically , we know that ith index variable is independent variable , so we are giving it 1 value
            #Now in the next loop, we will find all the dependent variable that are dependent on xi or this ith variable
            dummy[i]=1
            dummy2=dummy.copy()
            for j in b:
                k=0
                #Finding the row in which the jth pivot column exists
                for t in range(m):
                    if A[t,j]==1:
                        k=t
                        #Giving the j-th variable this value as it is dependent on the i th variable and the ith variable is given thevalue of 1
                        dummy2[j]= -A[k,i]
                        break
            null_space.append(dummy2)
            #The Function is returning the basis of null space(an array of Rn*1 vectors basically) and the dimension of the null space
    
    return null_space,len(null_space)
    

In [6]:
if __name__ == '__main__':
    Matrices = [] 
    Mnames = [] 
    
    A = np.matrix([[1.,2.,0.],[4.,5.,0.],[0.,0.,0.]])
    Matrices.append(A)
    Mnames.append('A')
    
    B = np.matrix([[0.,0.,0.],[0.,0.,0.],[0.,0.,0.]])
    Matrices.append(B)
    Mnames.append('B')
    
    C = np.matrix([[1.,2.,3.,4.,5.],[2.,3.,4.,5.,6.]])
    Matrices.append(C)
    Mnames.append('C')
    
    D = np.matrix([[1.,2.,3.], [2.,4.,6], [7.,8.,9], [3.,6.,9], [10.,14.,18.] ] )
    Matrices.append(D)
    Mnames.append('D')
    
    E = np.matrix([[ 0., -1., -2.],[ 1.,  0., -1.],[ 2.,  1.,  0.]])
    Matrices.append(E)
    Mnames.append('E')
    
    F = np.matrix([[  1., 1/2., 1/3., 1/4., 1/5.],[  2.,   1., 2/3., 1/2., 2/5.],[  3., 3/2.,   1., 3/4., 3/5.],[  4.,   2., 4/3.,   1., 4/5.],[  5., 5/2., 5/3., 5/4.,   1.]])
    Matrices.append(F)
    Mnames.append('F')
    
    G = np.matrix([[0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],[1., 0., 1., 0., 0., 0., 1., 0., 0., 0.],[0., 1., 0., 1., 0., 0., 0., 1., 0., 0.],[0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],[1., 0., 0., 1., 0., 0., 0., 0., 0., 1.],[1., 0., 0., 0., 0., 0., 0., 1., 1., 0.],[0., 1., 0., 0., 0., 0., 0., 0., 1., 1.],[0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],[0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],[0., 0., 0., 0., 1., 0., 1., 1., 0., 0.]])
    Matrices.append(G)
    Mnames.append('G')
    
    H = np.matrix([[1., 2., 3., 4., 8.],[8., 1., 2., 3., 4.],[4., 8., 1., 2., 3.],[3., 4., 8., 1., 2.],[2., 3., 4., 8., 1.]])
    Matrices.append(H)
    Mnames.append('H')
    
    I = np.matrix([[ 0.,  3.,  6.,  9., 12., 15., 18., 21.],[ 1.,  4.,  7., 10., 13., 16., 19., 22.],[ 2.,  5.,  8., 11., 14., 17., 20., 23.]])
    Matrices.append(I)
    Mnames.append('I')
    
    J = np.matrix([[0., 0., 0., 0., 2.],[1., 0., 0., 0., 3.],[0., 1., 0., 0., 4.],[0., 0., 1., 0., 5.],[0., 0., 0., 1., 6.]])
    Matrices.append(J)
    Mnames.append('J')
    
    K = np.matrix([[6., 5., 4., 3., 2.], [1., 0., 0., 0., 0.],[0., 1., 0., 0., 0.],[0., 0., 1., 0., 0.],[0., 0., 0., 1., 0.]])
    Matrices.append(K)
    Mnames.append('K')
    
    L = np.matrix([[0., 1., 0., 0., 0.],[0., 0., 1., 0., 0.],[0., 0., 0., 1., 0.],[0., 0., 0., 0., 1.],[2., 3., 4., 5., 6.]])
    Matrices.append(L)
    Mnames.append('L')
    
    M = np.matrix([[6., 1., 0., 0., 0.],[5., 0., 1., 0., 0.],[4., 0., 0., 1., 0.],[3., 0., 0., 0., 1.],[2., 0., 0., 0., 0.]])
    Matrices.append(M)
    Mnames.append('M')
    
    N = np.matrix([[  90.,  -80.,   56., -448., -588.],[  60.,    0.,   28., -324., -204.],[  60.,  -72.,   32., -264., -432.],[  30.,  -16.,   16., -152., -156.],[ -10.,   -8.,   -4.,   60.,    8.]])
    Matrices.append(N)
    Mnames.append('N')
    
    O = np.matrix([[ -15.,   -4.,   83.,   35.,  -24.,   47.,  -74.,  50.],[ -16.,   -7.,   94.,   34.,  -25.,   38.,  -75.,   50.,],[  89.,   34., -513., -196.,  141., -235.,  426., -285.],[  17.,    6.,  -97.,  -38.,   27.,  -47.,   82.,  -55.],[   7.,    3.,  -41.,  -15.,   11.,  -17.,   33.,  -22.],[  -5.,   -2.,   29.,   11.,   -8.,   13.,  -24.,   16.]])
    Matrices.append(O)
    Mnames.append('O')
    
    P = np.matrix([[    1.,     2.,     8.,   -35.,  -178.,  -239.,  -284.,   778.],[    4.,     9.,    37.,  -163.,  -827., -1111., -1324.,  3624.],[    5.,     6.,    21.,   -88.,  -454.,  -607.,  -708.,  1951.],[   -4.,    -5.,   -22.,    97.,   491.,   656.,   779., -2140.],[    4.,     4.,    13.,   -55.,  -283.,  -377.,  -436.,  1206.],[    4.,    11.,    43.,  -194.,  -982., -1319., -1576.,  4310.],[   -1.,    -2.,   -13.,    59.,   294.,   394.,   481., -1312.]])
    Matrices.append(P)
    Mnames.append('P')
    
    Q = np.matrix ([[    1.,     1.,     7.,   -29.,   139.,   206.,   413.],[   -2.,    -1.,   -10.,    41.,  -197.,  -292.,  -584.],[    2.,     5.,    27.,  -113.,   541.,   803.,  1618.],[    4.,     0.,    14.,   -55.,   268.,   399.,   798.],[    3.,     1.,     8.,   -32.,   152.,   218.,   412.],[   -3.,    -2.,   -18.,    70.,  -343.,  -506., -1001.],[    1.,    -2.,    -1.,     1.,    -2.,     9.,    52.]])
    Matrices.append(Q)
    Mnames.append('Q')
    
    
    for m in np.arange(0,len(Mnames)):
        print('matrix %s:' %(Mnames[m]))
        print(Matrices[m])
        #find the rref 
        #rref_m = find_rref(Matrices[m])
        #print('rref of matrix %s:' %(Mnames[m]))
        #print(rref_m)
        
        #find the rowspace and its dimension 
        basis_null_space,dim_null_space = null_space(Matrices[m])
        #print(rowspace_basis_indices)
        print('Basis of null space of this matrix is %s: ' %(basis_null_space))
        #print( (Matrices[m])[rowspace_basis_indices])
        print('dimension of null space of matrix %s: %d' %(Mnames[m],dim_null_space))
        #row_space_dim_of_different_matrices.append(rowspace_dim)
        print('***********************************************')
        
        
        

matrix A:
[[1. 2. 0.]
 [4. 5. 0.]
 [0. 0. 0.]]
num rows: 3
num cols: 3
num rows: 3
num cols: 3
Basis of null space of this matrix is [array([[-0.],
       [ 0.],
       [ 1.]])]: 
dimension of null space of matrix A: 1
***********************************************
matrix B:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
num rows: 3
num cols: 3
num rows: 3
num cols: 3
Basis of null space of this matrix is [array([[1.],
       [0.],
       [0.]]), array([[0.],
       [1.],
       [0.]]), array([[0.],
       [0.],
       [1.]])]: 
dimension of null space of matrix B: 3
***********************************************
matrix C:
[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]]
num rows: 2
num cols: 5
num rows: 2
num cols: 5
Basis of null space of this matrix is [array([[ 1.],
       [-2.],
       [ 1.],
       [ 0.],
       [ 0.]]), array([[ 2.],
       [-3.],
       [ 0.],
       [ 1.],
       [ 0.]]), array([[ 3.],
       [-4.],
       [ 0.],
       [ 0.],
       [ 1.]])]: 
dimension of null space of matrix C

In [7]:
##Using the matrix  G

G = np.matrix([[0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],[1., 0., 1., 0., 0., 0., 1., 0., 0., 0.],[0., 1., 0., 1., 0., 0., 0., 1., 0., 0.],[0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],[1., 0., 0., 1., 0., 0., 0., 0., 0., 1.],[1., 0., 0., 0., 0., 0., 0., 1., 1., 0.],[0., 1., 0., 0., 0., 0., 0., 0., 1., 1.],[0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],[0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],[0., 0., 0., 0., 1., 0., 1., 1., 0., 0.]])


In [8]:
G

matrix([[0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
        [0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 1., 1., 0., 0.]])

Lets find the basis and dimension of the eigen space $E_{\lambda 1}$, when $\lambda_{1} = -2$ . So we basically have to find  $N(G-    \lambda_{1} \times I)$



In [9]:
# H = G- lambda *I

H= G- (-2)*np.eye(G.shape[0],G.shape[0])
x,y=null_space(H)
print('The Dimension of eigen space when lambda= -2 is :',y)
print('Basis for eigen space of G when lambda = -2 is %s'%(x))
print('********************************************************')

num rows: 10
num cols: 10
num rows: 10
num cols: 10
The Dimension of eigen space when lambda= -2 is : 4
Basis for eigen space of G when lambda = -2 is [array([[ 1.9999999999999996e+00],
       [-1.9999999999999996e+00],
       [ 9.9999999999999989e-01],
       [-1.1102230246251565e-16],
       [-9.9999999999999978e-01],
       [-9.9999999999999989e-01],
       [ 1.0000000000000000e+00],
       [ 0.0000000000000000e+00],
       [ 0.0000000000000000e+00],
       [ 0.0000000000000000e+00]]), array([[ 1.0000000000000002e+00],
       [-2.2204460492503131e-16],
       [-9.9999999999999978e-01],
       [ 9.9999999999999978e-01],
       [-1.0000000000000000e+00],
       [-1.0000000000000002e+00],
       [ 0.0000000000000000e+00],
       [ 1.0000000000000000e+00],
       [ 0.0000000000000000e+00],
       [ 0.0000000000000000e+00]]), array([[ 9.9999999999999933e-01],
       [-9.9999999999999956e-01],
       [ 9.9999999999999989e-01],
       [-1.0000000000000002e+00],
       [ 4.4408920985006262e

### ----------------------------------------------------------------------------------------

Lets find the basis and dimension of the eigen space $E_{\lambda_2}$, when $\lambda_{2} = 1$ . So we basically have to find  $N(G-    \lambda_{2} \times I)$



In [10]:
# H = G- lambda *I

H= G- (1)*np.eye(G.shape[0],G.shape[0])
x,y=null_space(H)
print('The Dimension of eigen space when lambda= 1 is :',y)
print('Basis for eigen space of G when lambda =1 is %s'%(x))
print('********************************************************')

num rows: 10
num cols: 10
num rows: 10
num cols: 10
The Dimension of eigen space when lambda= 1 is : 5
Basis for eigen space of G when lambda =1 is [array([[ 1.],
       [-0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]]), array([[-0.],
       [ 1.],
       [-0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.]]), array([[-1.],
       [-0.],
       [ 1.],
       [-0.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.]]), array([[-1.],
       [-1.],
       [-0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.]]), array([[-0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.]])]
********************************************************


### ----------------------------------------------------------------------------------------

Lets find the basis and dimension of the eigen space $E_{\lambda_3}$, when $\lambda_{3} = 3$ . So we basically have to find  $N(G-    \lambda_{3} \times I)$



In [11]:
# H = G- lambda *I

H= G- (3)*np.eye(G.shape[0],G.shape[0])
x,y=null_space(H)
print('The Dimension of eigen space when lambda= 3 is :',y)
print('Basis for eigen space of G when lambda = 3 is %s'%(x))
print('********************************************************')

num rows: 10
num cols: 10
num rows: 10
num cols: 10
The Dimension of eigen space when lambda= 3 is : 1
Basis for eigen space of G when lambda = 3 is [array([[0.9999999999999998],
       [0.9999999999999998],
       [0.9999999999999998],
       [1.                ],
       [0.9999999999999999],
       [0.9999999999999999],
       [0.9999999999999997],
       [0.9999999999999999],
       [0.9999999999999998],
       [1.                ]])]
********************************************************
