# Name: Shubham Sharma
## IIT BOMBAY
This code is basically deals with how we can make a code to find basis to row space and basis to column space of a matrix

In [1]:
import numpy as np
np.set_printoptions(precision=16)
import math

In [2]:
#algorithm to find the index of first non-zero element in a column from position start_row 
def find_nonzero_element_index(col, start_row):
    #print(col)
    ret_index = -1
    for k in np.arange(start_row,col.size):
        #print('is close to zero: %s' %(math.isclose(np.abs(col[k]), 0., abs_tol=1e-13)))
        if not math.isclose(np.abs(col[k]), 0., abs_tol=1e-13):
            ret_index = k
            break
    #print ('ret index: %d' %(ret_index))
    return ret_index

In [3]:
#algorithm to convert a matrix A to rref
#algorithm to convert a matrix A to rref
def find_rref(A):
    #print(A.shape)
    m = (A.shape)[0] #num rows
    n = (A.shape)[1] #num cols
    print('num rows: %d' %(m))
    print('num cols: %d' %(n))

    j = 0
    r = 0
    
    B=A.copy()
    
    for j in np.arange(0,n):
        non_zero_row_index = find_nonzero_element_index(B[:,j],r)
        #print('r: %d' %(r))
        if non_zero_row_index != -1: 
            #write the code to make the pivot element in the non-zero row as 1 
            #and to make all other elements in the pivot column as zero  
            
            #If non_zero index is greater than the r then we will interschange the two rows
            if non_zero_row_index>r:
                c=r
                B[[non_zero_row_index,r]]=B[[r,non_zero_row_index]]
            else:
                c=non_zero_row_index
            B[c,:]=B[c,:]/B[c,j]
            
            
            #performimg the row operations
            for i in range(m):
                if i!=c:
                    B[i,:]=B[i,:]-B[i,j]*B[c,:]
            
            #you can check your code by printing the intermediate matrix using the following statement
            #print('rref process in col: %d ' %(j))
            #print(A)
            r = r+1
    return (B)



In [4]:
#returns the non-zero row indices and dimension of rowspace(A)
def find_rowspace_basis_dim(rref_A):
    m = (rref_A.shape)[0]
    non_zero_indices = [] 
    start_index = 0
    for i in np.arange(0,m):
        non_zero_pos = find_nonzero_element_index(rref_A[i].T,start_index)
        if non_zero_pos != -1:
            start_index = non_zero_pos
            non_zero_indices.append(non_zero_pos)
        else:
            break
    return non_zero_indices, len(non_zero_indices)


# Answer to question 2 of the assignment

In [5]:
if __name__ == '__main__':
    Matrices = [] 
    Mnames = [] 
    
    A = np.matrix([[1.,2.,0.],[4.,5.,0.],[0.,0.,0.]])
    Matrices.append(A)
    Mnames.append('A')
    
    B = np.matrix([[0.,0.,0.],[0.,0.,0.],[0.,0.,0.]])
    Matrices.append(B)
    Mnames.append('B')
    
    C = np.matrix([[1.,2.,3.,4.,5.],[2.,3.,4.,5.,6.]])
    Matrices.append(C)
    Mnames.append('C')
    
    D = np.matrix([[1.,2.,3.], [2.,4.,6], [7.,8.,9], [3.,6.,9], [10.,14.,18.] ] )
    Matrices.append(D)
    Mnames.append('D')
    
    E = np.matrix([[ 0., -1., -2.],[ 1.,  0., -1.],[ 2.,  1.,  0.]])
    Matrices.append(E)
    Mnames.append('E')
    
    F = np.matrix([[  1., 1/2., 1/3., 1/4., 1/5.],[  2.,   1., 2/3., 1/2., 2/5.],[  3., 3/2.,   1., 3/4., 3/5.],[  4.,   2., 4/3.,   1., 4/5.],[  5., 5/2., 5/3., 5/4.,   1.]])
    Matrices.append(F)
    Mnames.append('F')
    
    G = np.matrix([[0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],[1., 0., 1., 0., 0., 0., 1., 0., 0., 0.],[0., 1., 0., 1., 0., 0., 0., 1., 0., 0.],[0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],[1., 0., 0., 1., 0., 0., 0., 0., 0., 1.],[1., 0., 0., 0., 0., 0., 0., 1., 1., 0.],[0., 1., 0., 0., 0., 0., 0., 0., 1., 1.],[0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],[0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],[0., 0., 0., 0., 1., 0., 1., 1., 0., 0.]])
    Matrices.append(G)
    Mnames.append('G')
    
    H = np.matrix([[1., 2., 3., 4., 8.],[8., 1., 2., 3., 4.],[4., 8., 1., 2., 3.],[3., 4., 8., 1., 2.],[2., 3., 4., 8., 1.]])
    Matrices.append(H)
    Mnames.append('H')
    
    I = np.matrix([[ 0.,  3.,  6.,  9., 12., 15., 18., 21.],[ 1.,  4.,  7., 10., 13., 16., 19., 22.],[ 2.,  5.,  8., 11., 14., 17., 20., 23.]])
    Matrices.append(I)
    Mnames.append('I')
    
    J = np.matrix([[0., 0., 0., 0., 2.],[1., 0., 0., 0., 3.],[0., 1., 0., 0., 4.],[0., 0., 1., 0., 5.],[0., 0., 0., 1., 6.]])
    Matrices.append(J)
    Mnames.append('J')
    
    K = np.matrix([[6., 5., 4., 3., 2.], [1., 0., 0., 0., 0.],[0., 1., 0., 0., 0.],[0., 0., 1., 0., 0.],[0., 0., 0., 1., 0.]])
    Matrices.append(K)
    Mnames.append('K')
    
    L = np.matrix([[0., 1., 0., 0., 0.],[0., 0., 1., 0., 0.],[0., 0., 0., 1., 0.],[0., 0., 0., 0., 1.],[2., 3., 4., 5., 6.]])
    Matrices.append(L)
    Mnames.append('L')
    
    M = np.matrix([[6., 1., 0., 0., 0.],[5., 0., 1., 0., 0.],[4., 0., 0., 1., 0.],[3., 0., 0., 0., 1.],[2., 0., 0., 0., 0.]])
    Matrices.append(M)
    Mnames.append('M')
    
    N = np.matrix([[  90.,  -80.,   56., -448., -588.],[  60.,    0.,   28., -324., -204.],[  60.,  -72.,   32., -264., -432.],[  30.,  -16.,   16., -152., -156.],[ -10.,   -8.,   -4.,   60.,    8.]])
    Matrices.append(N)
    Mnames.append('N')
    
    O = np.matrix([[ -15.,   -4.,   83.,   35.,  -24.,   47.,  -74.,  50.],[ -16.,   -7.,   94.,   34.,  -25.,   38.,  -75.,   50.,],[  89.,   34., -513., -196.,  141., -235.,  426., -285.],[  17.,    6.,  -97.,  -38.,   27.,  -47.,   82.,  -55.],[   7.,    3.,  -41.,  -15.,   11.,  -17.,   33.,  -22.],[  -5.,   -2.,   29.,   11.,   -8.,   13.,  -24.,   16.]])
    Matrices.append(O)
    Mnames.append('O')
    
    P = np.matrix([[    1.,     2.,     8.,   -35.,  -178.,  -239.,  -284.,   778.],[    4.,     9.,    37.,  -163.,  -827., -1111., -1324.,  3624.],[    5.,     6.,    21.,   -88.,  -454.,  -607.,  -708.,  1951.],[   -4.,    -5.,   -22.,    97.,   491.,   656.,   779., -2140.],[    4.,     4.,    13.,   -55.,  -283.,  -377.,  -436.,  1206.],[    4.,    11.,    43.,  -194.,  -982., -1319., -1576.,  4310.],[   -1.,    -2.,   -13.,    59.,   294.,   394.,   481., -1312.]])
    Matrices.append(P)
    Mnames.append('P')
    
    Q = np.matrix ([[    1.,     1.,     7.,   -29.,   139.,   206.,   413.],[   -2.,    -1.,   -10.,    41.,  -197.,  -292.,  -584.],[    2.,     5.,    27.,  -113.,   541.,   803.,  1618.],[    4.,     0.,    14.,   -55.,   268.,   399.,   798.],[    3.,     1.,     8.,   -32.,   152.,   218.,   412.],[   -3.,    -2.,   -18.,    70.,  -343.,  -506., -1001.],[    1.,    -2.,    -1.,     1.,    -2.,     9.,    52.]])
    Matrices.append(Q)
    Mnames.append('Q')
    
    row_space_dim_of_different_matrices=[]
    #This array will help us to find if the dim of row space is equal to the column space
    
    for m in np.arange(0,len(Mnames)):
        print('matrix %s:' %(Mnames[m]))
        print(Matrices[m])
        #find the rref 
        rref_m = find_rref(Matrices[m])
        print('rref of matrix %s:' %(Mnames[m]))
        print(rref_m)
        
        #find the rowspace and its dimension 
        rowspace_basis_indices, rowspace_dim = find_rowspace_basis_dim(rref_m)
        print(rowspace_basis_indices)
        print('Rowspace Basis of matrix %s: ' %(Mnames[m]))
        print( (Matrices[m])[rowspace_basis_indices])
        print('Rowspace dimension of matrix %s: %d' %(Mnames[m],rowspace_dim))
        row_space_dim_of_different_matrices.append(rowspace_dim)
        print('***********************************************')
        
        
        #N,O,P,Q==3,3,6,7;

matrix A:
[[1. 2. 0.]
 [4. 5. 0.]
 [0. 0. 0.]]
num rows: 3
num cols: 3
rref of matrix A:
[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  0.]]
[0, 1]
Rowspace Basis of matrix A: 
[[1. 2. 0.]
 [4. 5. 0.]]
Rowspace dimension of matrix A: 2
***********************************************
matrix B:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
num rows: 3
num cols: 3
rref of matrix B:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[]
Rowspace Basis of matrix B: 
[]
Rowspace dimension of matrix B: 0
***********************************************
matrix C:
[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]]
num rows: 2
num cols: 5
rref of matrix C:
[[ 1.  0. -1. -2. -3.]
 [-0.  1.  2.  3.  4.]]
[0, 1]
Rowspace Basis of matrix C: 
[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]]
Rowspace dimension of matrix C: 2
***********************************************
matrix D:
[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 7.  8.  9.]
 [ 3.  6.  9.]
 [10. 14. 18.]]
num rows: 5
num cols: 3
rref of matrix D:
[[ 1.  0. -1.]
 [-0.  1.  2.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]


In [6]:
# This is the array of the dim of the row space
row_space_dim_of_different_matrices

[2, 0, 2, 2, 2, 1, 10, 5, 2, 5, 5, 5, 5, 3, 3, 6, 7]

# In the code for finding the basis and dimension of the column space, we'll use the row reduced echlon form of the given matrix and will extract the pivot columns that will give us the basis and the number of pivot columns will give us the dimension of the basis of the column space

In [7]:
# defining a function to extract set of linearly independent columns/basis of column space with the help of RREF

def extract_column_basis(A):
    #B=find_rref(A)
    #Finding the pivot columns index
    B=find_rref(A)
    #print('The rref of the given matrix is : ',)
    x=[]
    (m,n)=B.shape
    for i in range(m):
        for j in range(n):
            if B[i,j]==1:
                x.append(j)
                break    
    
    column_basis=[]
    for k in x:
        column_basis.append(A[:,k])
    
    return column_basis, len(column_basis)

# Finding the Basis of the Column space and the dimension for the given matrix we have. As basis is a set of linearly independent vectors, we have defined the basis in such a way that it contains set of column vectors(matrices)

In [8]:
if __name__ == '__main__':
    Matrices = [] 
    Mnames = [] 
    
    A = np.matrix([[1.,2.,0.],[4.,5.,0.],[0.,0.,0.]])
    Matrices.append(A)
    Mnames.append('A')
    
    B = np.matrix([[0.,0.,0.],[0.,0.,0.],[0.,0.,0.]])
    Matrices.append(B)
    Mnames.append('B')
    
    C = np.matrix([[1.,2.,3.,4.,5.],[2.,3.,4.,5.,6.]])
    Matrices.append(C)
    Mnames.append('C')
    
    D = np.matrix([[1.,2.,3.], [2.,4.,6], [7.,8.,9], [3.,6.,9], [10.,14.,18.] ] )
    Matrices.append(D)
    Mnames.append('D')
    
    E = np.matrix([[ 0., -1., -2.],[ 1.,  0., -1.],[ 2.,  1.,  0.]])
    Matrices.append(E)
    Mnames.append('E')
    
    F = np.matrix([[  1., 1/2., 1/3., 1/4., 1/5.],[  2.,   1., 2/3., 1/2., 2/5.],[  3., 3/2.,   1., 3/4., 3/5.],[  4.,   2., 4/3.,   1., 4/5.],[  5., 5/2., 5/3., 5/4.,   1.]])
    Matrices.append(F)
    Mnames.append('F')
    
    G = np.matrix([[0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],[1., 0., 1., 0., 0., 0., 1., 0., 0., 0.],[0., 1., 0., 1., 0., 0., 0., 1., 0., 0.],[0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],[1., 0., 0., 1., 0., 0., 0., 0., 0., 1.],[1., 0., 0., 0., 0., 0., 0., 1., 1., 0.],[0., 1., 0., 0., 0., 0., 0., 0., 1., 1.],[0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],[0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],[0., 0., 0., 0., 1., 0., 1., 1., 0., 0.]])
    Matrices.append(G)
    Mnames.append('G')
    
    H = np.matrix([[1., 2., 3., 4., 8.],[8., 1., 2., 3., 4.],[4., 8., 1., 2., 3.],[3., 4., 8., 1., 2.],[2., 3., 4., 8., 1.]])
    Matrices.append(H)
    Mnames.append('H')
    
    I = np.matrix([[ 0.,  3.,  6.,  9., 12., 15., 18., 21.],[ 1.,  4.,  7., 10., 13., 16., 19., 22.],[ 2.,  5.,  8., 11., 14., 17., 20., 23.]])
    Matrices.append(I)
    Mnames.append('I')
    
    J = np.matrix([[0., 0., 0., 0., 2.],[1., 0., 0., 0., 3.],[0., 1., 0., 0., 4.],[0., 0., 1., 0., 5.],[0., 0., 0., 1., 6.]])
    Matrices.append(J)
    Mnames.append('J')
    
    K = np.matrix([[6., 5., 4., 3., 2.], [1., 0., 0., 0., 0.],[0., 1., 0., 0., 0.],[0., 0., 1., 0., 0.],[0., 0., 0., 1., 0.]])
    Matrices.append(K)
    Mnames.append('K')
    
    L = np.matrix([[0., 1., 0., 0., 0.],[0., 0., 1., 0., 0.],[0., 0., 0., 1., 0.],[0., 0., 0., 0., 1.],[2., 3., 4., 5., 6.]])
    Matrices.append(L)
    Mnames.append('L')
    
    M = np.matrix([[6., 1., 0., 0., 0.],[5., 0., 1., 0., 0.],[4., 0., 0., 1., 0.],[3., 0., 0., 0., 1.],[2., 0., 0., 0., 0.]])
    Matrices.append(M)
    Mnames.append('M')
    
    N = np.matrix([[  90.,  -80.,   56., -448., -588.],[  60.,    0.,   28., -324., -204.],[  60.,  -72.,   32., -264., -432.],[  30.,  -16.,   16., -152., -156.],[ -10.,   -8.,   -4.,   60.,    8.]])
    Matrices.append(N)
    Mnames.append('N')
    
    O = np.matrix([[ -15.,   -4.,   83.,   35.,  -24.,   47.,  -74.,  50.],[ -16.,   -7.,   94.,   34.,  -25.,   38.,  -75.,   50.,],[  89.,   34., -513., -196.,  141., -235.,  426., -285.],[  17.,    6.,  -97.,  -38.,   27.,  -47.,   82.,  -55.],[   7.,    3.,  -41.,  -15.,   11.,  -17.,   33.,  -22.],[  -5.,   -2.,   29.,   11.,   -8.,   13.,  -24.,   16.]])
    Matrices.append(O)
    Mnames.append('O')
    
    P = np.matrix([[    1.,     2.,     8.,   -35.,  -178.,  -239.,  -284.,   778.],[    4.,     9.,    37.,  -163.,  -827., -1111., -1324.,  3624.],[    5.,     6.,    21.,   -88.,  -454.,  -607.,  -708.,  1951.],[   -4.,    -5.,   -22.,    97.,   491.,   656.,   779., -2140.],[    4.,     4.,    13.,   -55.,  -283.,  -377.,  -436.,  1206.],[    4.,    11.,    43.,  -194.,  -982., -1319., -1576.,  4310.],[   -1.,    -2.,   -13.,    59.,   294.,   394.,   481., -1312.]])
    Matrices.append(P)
    Mnames.append('P')
    
    Q = np.matrix ([[    1.,     1.,     7.,   -29.,   139.,   206.,   413.],[   -2.,    -1.,   -10.,    41.,  -197.,  -292.,  -584.],[    2.,     5.,    27.,  -113.,   541.,   803.,  1618.],[    4.,     0.,    14.,   -55.,   268.,   399.,   798.],[    3.,     1.,     8.,   -32.,   152.,   218.,   412.],[   -3.,    -2.,   -18.,    70.,  -343.,  -506., -1001.],[    1.,    -2.,    -1.,     1.,    -2.,     9.,    52.]])
    Matrices.append(Q)
    Mnames.append('Q')
    
    column_space_dim_of_different_matrices=[]
    #This array will help us to find if the dim of row space is equal to the column space
    
    for m in np.arange(0,len(Mnames)):
        print('matrix %s:' %(Mnames[m]))
        print(Matrices[m])
        
        #find the column-space and its dimension 
        column_basis, column_dim = extract_column_basis(Matrices[m])
        column_space_dim_of_different_matrices.append(column_dim)
        #print(column_basis)
        print('column Basis of matrix %s: ' %(Mnames[m]))
        print( (column_basis))
        print('Column Space dimension of matrix %s: %d' %(Mnames[m],column_dim))
        print('***********************************************')
        
        

matrix A:
[[1. 2. 0.]
 [4. 5. 0.]
 [0. 0. 0.]]
num rows: 3
num cols: 3
column Basis of matrix A: 
[matrix([[1.],
        [4.],
        [0.]]), matrix([[2.],
        [5.],
        [0.]])]
Column Space dimension of matrix A: 2
***********************************************
matrix B:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
num rows: 3
num cols: 3
column Basis of matrix B: 
[]
Column Space dimension of matrix B: 0
***********************************************
matrix C:
[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]]
num rows: 2
num cols: 5
column Basis of matrix C: 
[matrix([[1.],
        [2.]]), matrix([[2.],
        [3.]])]
Column Space dimension of matrix C: 2
***********************************************
matrix D:
[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 7.  8.  9.]
 [ 3.  6.  9.]
 [10. 14. 18.]]
num rows: 5
num cols: 3
column Basis of matrix D: 
[matrix([[ 1.],
        [ 2.],
        [ 7.],
        [ 3.],
        [10.]]), matrix([[ 2.],
        [ 4.],
        [ 8.],
        [ 6.],
        [14.]])]
Col

In [9]:
# This is the array of the dim of the column space
column_space_dim_of_different_matrices

[2, 0, 2, 2, 2, 1, 10, 5, 2, 5, 5, 5, 5, 3, 3, 6, 7]

# In order to check if the dim of row space is equal to the dim of the column space, we equate the two arrays of the dimension of the row space and the column space

In [10]:
column_space_dim_of_different_matrices==row_space_dim_of_different_matrices

True

# So we can see from above that dimension of the row space is equal to the dimension of the column space for every case given